### ISSUE TITLE
is user a stringified JSON?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [BigShanJohn/registration-service#2]
https://github.com/BigShanJohn/registration-service/blob/6a52007e7fd0012d6bf50ccba173da5d7ad6ef3d/managers/user-manager.js#L5

I am not familiar with the redis lib you are using.
The question is: is the _user_ parameter a stringified JSON object?

**Comment by BigShanJohn** [comment]
yes it is a JSON object, you can check it   on models/user.js  file

**Comment by BigShanJohn** [comment]
client.hmset(user.email, user, function(err, reply) {  . it is use to store JSON object

**Comment by Dmitry-N-Medvedev** [comment]
> yes it is a JSON object, you can check it on models/user.js file

the question is: is this JSON object saved to a hashmap as a string?

**Comment by BigShanJohn** [comment]
> JSON object saved to a hashmap as a string?

Yes. in Redis Hash.  I think using SET is the best approach. sorry I am new to Redis.  https://stackoverflow.com/questions/16375188/redis-strings-vs-redis-hashes-to-represent-json-efficiency

**Comment by BigShanJohn** [comment]
I will work on that and get back to you

**Comment by Dmitry-N-Medvedev** [comment]
> Yes. in Redis Hash.

the question is if you save it as a _stringify json_ to a hashmap?

**Comment by BigShanJohn** [comment]
> > Yes. in Redis Hash.
> 
> the question is if you save it as a _stringify json_ to a hashmap?

Oh, I got your question clearly now,  yes I save the stringify JSON to  a hashmap email since it is unique and I can easily call  the  record back

**Comment by Dmitry-N-Medvedev** [comment]
> I save the stringify JSON

I believe you should not save a stringify JSON to a redis hashmap.

**Comment by Dmitry-N-Medvedev** [comment]
> sorry I am new to Redis

this is not a problem. Redis has brilliant documentation. it would have taken you an hour reading about its data types like I had suggested.

**Comment by BigShanJohn** [comment]
Resolved the issue
